version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - php -v
      - echo COMPOSER_MEMORY_LIMIT=-1
      - echo "Installing Composer dependencies..."
      - composer install
    pre_build:
      commands:
        - echo "we are in the pre build phase"
    build:
      commands:
        - echo "we are in the build block"
    post_build:
      commands:
        - echo "we are in the post build phase"
        - rm composer.json
        - rm composer.lock
artifacts:
  files:
    - '**/*'
